Feat/pvp  ranked rewards on burnt chars
CryptoBlades/cryptoblades pull request #1120
Opened 2022-02-01 18:06 UTC by Jcalcaldev

This PR:

-Fixes an issue with restartRankedSeason if one of the top 3 players leaves the arena and deletes it's character.
-Updates shield minting in tests (broken since last week).
-Should add some gas saving in some functions by calling _ownerByCharacter instead of characters.ownerOf

2022-02-10 10:03 UTC, poshdan commented
Shouldn't isOwnedCharacter also use the new _ownerByCharacter value?

2022-02-10 17:48 UTC, Jcalcaldev commented
> Shouldn't isOwnedCharacter also use the new _ownerByCharacter value?

This is optimal but would cause some characters to be trapped in an invalid state in current ongoing networks (like BSC Testnet). Since _ownerByCharacter is set upon entering arena, players who have their characters already inside would not be able to leave and re-enter. I'm not sure how to approach this issue in the most optimal way.

2022-02-17 10:19 UTC, poshdan commented
It should be possible to expel players via an admin call.
The only concern there is gas, but on OEC it's very negligible.
We shouldn't be making compromises when a little elbow grease can help bridge the gap

2022-03-16 05:18 UTC, poshdan requested changes
one small change needed afaik

2022-03-16 05:18 UTC, poshdan commented on contracts/PvpArena.sol
>      mapping(uint256 => uint256) public specialWeaponRerollTimestamp;
the new mapping must come after the last state variable, please correct

2022-03-16 16:08 UTC, kcper approved these changes

2022-03-16 16:24 UTC, poshdan approved these changes

2022-03-16 16:25 UTC, merged