Add durability to weapons
CryptoBlades/cryptoblades pull request #291
Opened 2021-07-15 21:29 UTC by brian-man

This changes adds durability to weapons, similar to stamina for characters.

Importantly, durability is intended to limit a weapon's fight use to all 4 characters.  While the same maximum (200) could be used, the minimum needed is 1 durability per fight which maps to 20 durability.  A higher number can be used but it really should be a multiple of 20 (4 characters with 5 fights each per 16 hours).

I opted to use a mapping rather than adding a field to Weapon to align with the implementation for the transfer cooldown and to avoid potential issues with expanding Weapon.

Lastly, the need to apply a drain to two NFTs during a single operation (stamina for character and durability for weapon) must be done carefully to avoid draining one of them and failing a require when draining the other.

2021-07-15 21:48 UTC, newb23 commented
I've confirmed locally that this does indeed, work. 

`Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"message":"VM Exception while processing transaction: revert Not enough durability!","code":-32000,"data":{"0x17acf23d104dbd016fc9fbfa7e5df783a74618893490d79a8e76e763f371a577":{"error":"revert","program_counter":1123,"return":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000164e6f7420656e6f756768206475726162696c6974792100000000000000000000","reason":"Not enough durability!"},"stack":"c: VM Exception while processing transaction: revert Not enough durability!\n at Function.c.fromResults (/home/omni/.nvm/versions/node/v16.3.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\n at w.processBlock (/home/omni/.nvm/versions/node/v16.3.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:50915)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)","name":"c"}}}}`

2021-07-16 03:32 UTC, raymond-h approved these changes

2021-07-16 12:16 UTC, raymond-h requested changes
So to be honest I forgot about it at the time, but surely this also requires some frontend work before it can get merged.

2021-07-16 12:37 UTC, kcper commented
Starting the frontend work on it.

2021-07-16 14:54 UTC, kcper commented
All durabilities loaded when game loads.
Used weapon durability updates after combat.
All weapon durabilities updated every 10s.

https://user-images.githubusercontent.com/9114200/125966531-fcc7d449-bef0-4200-af9a-ed76dc1fd792.mp4

2021-07-21 16:12 UTC, seiyria approved these changes

2021-07-21 16:13 UTC, raymond-h approved these changes

2021-07-21 16:51 UTC, raymond-h requested changes
According to @kcper the frontend isn't actually ready quite yet to merge, so I'll mark this PR as "changes requested" so no one accidently merges it thinking it's fine just yet.

2021-07-22 22:42 UTC, raymond-h approved these changes

2021-07-22 22:44 UTC, merged