Move characterLimit member from cryptoblades.sol to characters.sol
CryptoBlades/cryptoblades pull request #389
Opened 2021-07-21 23:24 UTC by brian-man

2021-07-21 23:24 UTC, brian-man commented
@raymond-h Do we need to leave (but marked deprecated or something) the characterLimit config member in cryptoblades.sol?

2021-07-22 21:57 UTC, raymond-h requested changes

2021-07-22 21:57 UTC, raymond-h commented on contracts/cryptoblades.sol
> -    uint characterLimit;
State variables can never be removed due to proxy contract upgradeability. Instead, add `// UNUSED; KEPT FOR UPGRADEABILITY PROXY COMPATIBILITY` as a note above it.

2021-07-22 21:57 UTC, raymond-h commented on contracts/cryptoblades.sol
> +            string(abi.encodePacked("You can only have ",characters.characterLimit," characters!")));
I believe state variables of other contracts cannot be accessed like this. They need to be treated like getter functions. Also requires the state variable in question to be `public`.

```suggestion
        require(characters.balanceOf(msg.sender) < characters.characterLimit(),
            string(abi.encodePacked("You can only have ",characters.characterLimit()," characters!")));
```

2021-07-22 21:57 UTC, raymond-h commented on contracts/cryptoblades.sol
> +        require(characters.balanceOf(msg.sender) <= characters.characterLimit, "Too many characters owned");
I believe state variables of other contracts cannot be accessed like this. They need to be treated like getter functions. Also requires the state variable in question to be `public`.

```suggestion
        require(characters.balanceOf(msg.sender) <= characters.characterLimit(), "Too many characters owned");
```

2021-07-22 21:57 UTC, raymond-h commented on contracts/characters.sol
> +    uint characterLimit;
`uint` is shorthand for `uint256`, and I realize the original code in `cryptoblades.sol` itself used `uint` for this, but I think we should prefer explicitly stating it.

```suggestion
    uint256 characterLimit;
```

2021-07-22 21:57 UTC, raymond-h commented on contracts/characters.sol
> +        characterLimit = 4;
For now I don't intend to enforce it, but for the future: initialization of new state variables have to be done by a brand-new function as the initializer function was called exactly once - during the first deploy - and will never be called again.

Our convention has been to add a `migrateTo_XXXXXXX` function that gets called during deployment of the new version of the contract, where `XXXXXXX` is the 7 first characters of some relevant Git commit hash that introduced the changes. You can find examples by looking in several other files.

Do feel free to implement that if you wish, but once again, I don't intend to enforce it for now.

2021-07-26 22:28 UTC, raymond-h approved these changes

2021-07-26 22:46 UTC, merged