feature/330 - Allow hyperlinking to a specific weapon or character or (future nft)
CryptoBlades/cryptoblades pull request #447
Opened 2021-07-24 15:45 UTC by FilipBartos

### All Submissions

* [x] Can you post a screenshot of your changes (if applicable)?

NFT Listing

![image](https://user-images.githubusercontent.com/485811/126873721-f1087206-1951-4789-9b75-053f6458eee2.png)

NFT share action

![image](https://user-images.githubusercontent.com/485811/126873768-74029a2d-b432-4bdc-9aa2-7bf7c3ff713c.png)

NFT copied link result

![image](https://user-images.githubusercontent.com/485811/126873770-8662cee0-93e7-4a66-8edd-8adac54b15e4.png)

### New Feature Submissions

* [x] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?

https://github.com/CryptoBlades/cryptoblades/issues/330

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

(insert description here)

2021-07-24 15:53 UTC, seiyria commented
Can we get the share button to the left of the clear filters button? Having it on every weapon is a bit much. With it being there, it will allow sharing a set of market results better. We can add a share id option on the search nfts page, since that one is look up by id.

2021-07-24 16:21 UTC, seiyria commented on frontend/src/router.ts
> +      { path: '/market/:category/:type/:id', name: 'marketSearch', component: Market },
this should really all be query params on /market. we have a lot of search criteria to go through.

2021-07-24 16:43 UTC, FilipBartos commented
@seiyria sure, what about separate view - something like "seller's profile" that would list characters/weapons from specified seller address? Something like at the screens below:

![image](https://user-images.githubusercontent.com/485811/126875287-2e3f3568-d102-4fbd-9b45-f68e235e3b49.png)
![image](https://user-images.githubusercontent.com/485811/126875293-2fdfeaf3-f010-452a-abea-d69c45948d45.png)

2021-07-24 16:51 UTC, seiyria commented
Sure, we could do something like that. What you'll want to do is accept query parameters for everything that goes into the search query - seller address, element, minlevel, maxlevel, etc, and use that. then people can share their current settings much more easily than having more market routes.

2021-07-27 01:21 UTC, seiyria requested changes
conflicts need to be fixed, as well as the other change I requested

2021-07-29 13:54 UTC, seiyria commented on frontend/src/views/Seller.vue
> +      console.warn(this.items);
please remove console statements

2021-07-29 14:38 UTC, ultradeq commented
Hi @seiyria , what about placing the "share market link" (or something like "share my market") to the character display area (see attached image)? It would then copy the url .../market/seller/:accountAddress (where the user's items for sale would be listed) to the clipboard.
![cb-share-market-link](https://user-images.githubusercontent.com/4114345/127511823-b7d7276b-9f52-457d-8fb0-0738e8256922.jpg)

2021-07-29 15:13 UTC, seiyria commented
I think that location would be fine, but again, everything should be a query parameter. There should be no new routes for this.

2021-11-17 13:41 UTC, kcper commented
As there were no updates here, I resolved the issue using "..." menu with "Copy link" option and NFT Display component here: https://github.com/CryptoBlades/cryptoblades/pull/851

2021-11-17 13:41 UTC, closed without merging