Show sword forge bounty on 'Unlikely Victory' fights
CryptoBlades/cryptoblades pull request #480
Opened 2021-07-27 21:19 UTC by kcper

### All Submissions

* [ ] Can you post a screenshot of your changes (if applicable)?
![image](https://user-images.githubusercontent.com/9114200/127228310-e8f83125-1dd5-4bb7-9a3b-0b04cd02bc46.png)

### New Feature Submissions

* [ ] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?
N/A
### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

Highlighting and bounty icon on fights that are unlikely to be won.

2021-07-27 22:12 UTC, seiyria approved these changes

2021-07-27 22:12 UTC, seiyria commented
Looks good but I'll hold off on merging until the counterpart in solidity works.

2021-08-03 03:05 UTC, raymond-h requested changes
Weapons aren't forged automatically on win - instead the user is given a "ticket" that they can spend to mint a weapon instead of SKILL.

2021-08-04 11:57 UTC, kcper commented
Summary:
Forge with ticket button:
![image](https://user-images.githubusercontent.com/9114200/128176276-9b6032a2-99db-4b67-bd35-1d6634f63c9f.png)
Ticket amount picker if user has more than 1 ticket available:
![image](https://user-images.githubusercontent.com/9114200/128176324-ddb15cc7-43cd-4ae1-b421-01e88eb08b72.png)
Button if there are no tickets available, left disabled instead of hidden to show that there is this new ticket thing:
![image](https://user-images.githubusercontent.com/9114200/128176381-45e64988-a0eb-4df0-9270-18a301d60b3f.png)
Unlikely fight:
![image](https://user-images.githubusercontent.com/9114200/128176432-7179d61b-8554-4985-b57f-0a4806592e25.png)

2021-08-04 13:43 UTC, seiyria commented on frontend/src/store.ts
> +        console.log(num);
gotta remove the console.logs

2021-08-04 13:44 UTC, seiyria commented on frontend/src/views/Blacksmith.vue
> +      console.log(this.forgeTicketCount);
log

2021-08-04 13:45 UTC, seiyria approved these changes
overall UI looks good - I dig the idea and implementation. Just some console.logs but that's not going to hold this up.

2021-08-25 10:57 UTC, raymond-h approved these changes

2021-09-07 20:13 UTC, poshdan commented
This should be delayed until we have 100% safe randoms to plug into fights, else it will be abused.
Given that our best random-safety measure requires 2tx I'm not sure this feature is viable for us.

2021-12-07 20:47 UTC, closed without merging