Add fuction to mint N amount of weapons
CryptoBlades/cryptoblades pull request #539
Opened 2021-07-30 14:30 UTC by procart

Add fuction to mint N amount of weapons

2021-07-30 14:31 UTC, seiyria commented
you're a saint

2021-07-30 16:37 UTC, seiyria approved these changes

2021-08-03 01:07 UTC, raymond-h requested changes

2021-08-03 01:07 UTC, raymond-h commented on frontend/src/store.ts
> +        );
This will only approve enough SKILL for 1 weapon, not `num` weapons.

2021-08-03 01:07 UTC, raymond-h commented on contracts/cryptoblades.sol
> +        require(num > 0);
Better be safe than sorry and just enforce a maximum value as well. Can be changed easily later on anyway.

2021-08-03 01:35 UTC, raymond-h approved these changes

2021-08-03 02:11 UTC, merged