Remove base weapon power
CryptoBlades/cryptoblades pull request #566
Opened 2021-08-02 20:47 UTC by brian-man

2021-08-02 20:48 UTC, brian-man commented
There are many things being discussed in the "Motivating weapon upgrades" thread on Discord.

On specific idea was raised by Shyrus to remove the base weapon multiplier of 1.  This would make star count, stat alignment, and reforging more valuable than they are today.  It would also diminish significantly the effectiveness of 1star and 2star weapons, which is also good.

2021-08-02 20:55 UTC, seiyria approved these changes

2021-08-25 11:44 UTC, raymond-h approved these changes

2021-09-17 17:34 UTC, poshdan requested changes
I'm not sure we should add the base multiplier variable if we plan on it being 0.
The fact that this code is anticipating its change, makes me feel like it hasn't been thoroughly checked and finalized.
I'll try to make some time to test this myself but for the time being I'd like to hold it until at least others can take another look.

2021-09-17 17:34 UTC, poshdan commented on contracts/weapons.sol
> +        require(multiplier >= 0, "BaseWeaponMultiplier too low");
These require statements will always block the function.
int128 variables aren't inherently handled as fixed64x64 numbers so they can't be used for a fractional comparison
I also don't think these sanity checks should be kept at all.
I'd rather the function parameter took in a decimal number that we then divide by like 10k using ABDK to get the fraction we need.

2021-12-07 20:47 UTC, closed without merging