Weapon hashing no longer has 10 minute drama
CryptoBlades/cryptoblades pull request #644
Opened 2021-08-08 15:27 UTC by brian-man

2021-08-25 11:33 UTC, raymond-h requested changes

2021-08-25 11:33 UTC, raymond-h commented on contracts/cryptoblades.sol
> -    mapping(address => MintPaymentSkillDeposited) mintPaymentSkillDepositeds;
Removing these things will make the contract not backwards-compatible, so they must be left in.

2021-09-03 15:38 UTC, raymond-h commented
Fails to compile. Seems to be because IRandoms and ChainlinkRandoms were modified, but DummyRandoms was not modified to match.

2021-09-03 17:24 UTC, brian-man commented
@raymond-h The dummy randoms is probably a trivial thing to correct, but the bigger issue as that we can't seem to stop mucking with minting in other ways and it was 8 days between updated PR and review attention.  It's just not sustainable for me to keep merging against a moving target with a week+ turnaround for review time.

2021-12-07 20:47 UTC, closed without merging