Add reroll target button for 20% of the average skill reward
CryptoBlades/cryptoblades pull request #667
Opened 2021-08-13 20:41 UTC by WAYN-Games

### All Submissions

* [X] Can you post a screenshot of your changes (if applicable)?

![image](https://user-images.githubusercontent.com/47318939/129415748-2f27f8ec-44b1-4bae-ac89-66bada89e6d4.png)

### New Feature Submissions

* [X] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?
https://github.com/CryptoBlades/cryptoblades/issues/597

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

Add a button under "Choose New Weapon" to "Reroll Targets".
When clicking on "Reroll Targets", the player pay 20% (configurable through a setter) of the average reward he would have gotten from the fight for the maximum stamina available and get a new set of targets.
The change only affect the character/weapon couple.
The skill balance displayed on hte top rigth corner is not updated automatically (could not find how) but refreshing hte page show the skill is consumed.

The implementation meets the requirement but may not be optimal has I have limited experience in Solidity and Vue.js.

2021-08-25 11:40 UTC, raymond-h approved these changes

2021-08-25 11:40 UTC, raymond-h commented on contracts/cryptoblades.sol
> +        rerollFightCost = 20;
This needs to go in a new `migrateTo_[X]`-style function. Name said new function `migrateTo_PLACEHOLDER` for now.

2021-08-25 11:41 UTC, raymond-h requested changes

2021-08-25 11:41 UTC, raymond-h commented on contracts/cryptoblades.sol
> +        rerollFightCost = 20;
This needs to go in a new `migrateTo_[X]`-style function. Name said new function `migrateTo_PLACEHOLDER` for now.

2021-08-25 14:48 UTC, seiyria commented
@raymond-h this one may need to wait. @bilbolPrime has a skill shop smoke bomb idea for this, although I'm not sure if it's been done yet.

2021-08-25 15:16 UTC, WAYN-Games commented
@raymond-h , I think @seiyria refers to https://github.com/CryptoBlades/cryptoblades/pull/671
If I'm not mistaken, the smoke bomb from this PR will change the target for the character whatever the weapon.
Mine changes the target set for the couple character/weapon.

2021-09-03 15:46 UTC, raymond-h commented
It sounds like there needs to be a discussion about this "smoke bomb" ordeal.

2021-09-03 15:48 UTC, seiyria commented
Sorry, in the effort of reducing confusion we're going to go with the smoke bomb idea and work with that idea, as we want to rework most interactions that cost SKILL to use the SKILL shop somehow.

2021-09-03 15:48 UTC, closed without merging