Added a consent banner for Google Analytics #674
CryptoBlades/cryptoblades pull request #686
Opened 2021-08-20 13:43 UTC by Sellie96

![image](https://user-images.githubusercontent.com/60218956/130242047-fb5bebbe-e1a1-42ab-9771-0f5235abc226.png)

On Reject Cookies aren't saved for the user on visits

![image](https://user-images.githubusercontent.com/60218956/130242221-1377a0c6-68d6-4644-bec3-1d76229e7ad5.png)

On Accept Cookies persist between sessions

![image](https://user-images.githubusercontent.com/60218956/130242354-f4f9e048-f804-4c07-9aef-7019fdafb21c.png)

#674 

Added a Consent banner for the use of google analytics to display targeted ads and measure site data.

2021-08-20 13:53 UTC, seiyria requested changes

2021-08-20 13:53 UTC, seiyria commented on frontend/public/index.html
> +  <script src="//rawcdn.githack.com/Alex-D/Cookies-EU-banner/2.0.0/dist/cookies-eu-banner.min.js"></script>
is there a way we can install this instead of referencing someone elses code?

2021-08-20 13:53 UTC, seiyria commented on frontend/public/index.html
> +  <script src="../node_modules/cookies-eu-banner/dist/cookies-eu-banner.min.js"></script>
can this be referenced by `import 'cookies-eu-banner'` in a main file, instead of importing from node modules?

2021-08-20 19:53 UTC, JustinSibonga approved these changes

2021-08-20 20:03 UTC, seiyria commented
@JustinSibonga who are you?

2021-08-21 00:48 UTC, kevinunger commented
I copied the scripts/css from node_modules to public to load it from there. 
I also moved the loading of the google-ad script into the cookiesEuBanner function, to load it only when consent has been given.
When the google-ad script is loaded outside of that (like it was before) it's always setting the _gads cookie. 

In the future, we might use a vue plugin for analytics and ads. This way we can just do it the vue-way and use analytics and ads in the components more easily. This also enables event-tracking for GA, so more granular tracking can be done in the future.

2021-08-21 22:15 UTC, kevinunger commented
resolves #674

2021-08-23 14:52 UTC, seiyria approved these changes

2021-08-23 14:53 UTC, merged