transak integration #490
CryptoBlades/cryptoblades pull request #695
Opened 2021-08-21 17:19 UTC by EduardoGomez951020

### All Submissions

* [ ] Can you post a screenshot of your changes (if applicable)?

### New Feature Submissions

* [ ] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

(insert description here)

2021-08-21 17:56 UTC, seiyria commented on frontend/src/store.ts
> +        return 'https://global.transak.com/?apiKey=YOUR_PRODUCTION_API_KEY?defaultCryptoCurrency=BNB'; //INSERT API KEY TRANSAK
this should be marked as draft if we don't have an api key

2021-08-23 14:54 UTC, seiyria requested changes
needs an api key

2021-08-23 16:02 UTC, EduardoGomez951020 commented
Hi @seiyria. Where or how should I get the api key ? 

Is existing already on the .env file ? 

<img width="463" alt="Screen Shot 2021-08-23 at 11 01 54" src="https://user-images.githubusercontent.com/28773860/130479625-a55b2784-d557-4f35-9a64-8a9a5935545b.png">

2021-08-23 16:04 UTC, seiyria commented
@EduardoGomez951020 I have requested one from kroge, but as of right now there isn't one.

2021-09-14 21:13 UTC, EduardoGomez951020 commented
Hi @seiyria, any update about it ?

2021-09-17 15:49 UTC, seiyria commented
looks fine, it took a while to get the api key (it looks like they forgot about us). sorry for the delay. this needs a round of testing then it would be good to go if it all works.

2021-09-17 18:46 UTC, bilbolPrime commented
Created PR 742 with some modifications to this one. Had trouble cloning the repo.

2021-09-17 18:46 UTC, closed without merging