staking options
CryptoBlades/cryptoblades pull request #916
Opened 2021-12-14 17:14 UTC by kcper

### All Submissions

* [ ] Can you post a screenshot of your changes (if applicable)?
![image](https://user-images.githubusercontent.com/9114200/146046562-506a450f-92a4-4851-8855-df04b6c6307a.png)
![image](https://user-images.githubusercontent.com/9114200/146046756-230588d3-8243-42f6-8897-6dccd2c24909.png)

### New Feature Submissions

* [ ] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?
#889 #888 
### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

Added staking options for 90/180 days distribution time for SKILL/KING.
Added CBK Land staking options for each tier.

2021-12-17 10:32 UTC, Chriserus commented on frontend/src/components/StakeSelectorItem.vue
> +            {{ isNftStaking ? '/NFT' : '%' }}
I would opt for parent div (in  this case td) to be rendered based on isNftStaking condition, to not check the same thing twice. But it's minor, do it, or not, we're good :)

2021-12-17 10:32 UTC, Chriserus commented on frontend/src/components/smart/Staking.vue
> +            <div v-bind:class="isNftStaking ? 'd-flex align-items-center w-100' : 'flex_row'">
:class. no need to add "v-bind" part

2021-12-17 10:32 UTC, Chriserus commented on frontend/src/components/smart/Staking.vue
> +                <option v-for="x in (isDeposit ? ownedLandIds : stakedIds)" :value="x.id" :key="x.id">{{x.id}} (Tier {{x.tier}})</option>
"Tier" can be added to translations

2021-12-17 10:32 UTC, Chriserus commented on frontend/src/components/smart/Staking.vue
> +                  <b-form-select-option :value="null" disabled>Pick ID</b-form-select-option>
Missing translation

2021-12-17 10:32 UTC, Chriserus commented on frontend/src/components/smart/Staking.vue
> +          this.idToStake = null;
Why are we using nulls as initial values? In my opinion it should be undefined.

2021-12-17 10:32 UTC, Chriserus commented on frontend/src/components/smart/Staking.vue
> +  width: 100%;
Delete custom class, you can use w-100

2021-12-17 10:32 UTC, Chriserus commented on frontend/src/locales/en.json
> +      "yield": "YIELD",
Try to avoid uppercase text in translations, use css uppercase

2021-12-20 08:51 UTC, bilbolPrime requested changes

2021-12-28 08:34 UTC, bilbolPrime approved these changes

2021-12-28 08:42 UTC, Chriserus approved these changes

2021-12-29 16:32 UTC, merged